plugins:
  github_linkback_enabled:
    default: false
  github_linkback_projects:
    default: ""
    type: list
  github_linkback_access_token:
    default: ''
  github_badges_enabled:
    default: false
  github_badges_repo:
    default: ''
  github_permalinks_enabled:
    default: false
  github_permalinks_exclude:
    default: "README.md"
    type: list
  github_silver_badge_min_commits:
    default: 25
    min: 1
  github_gold_badge_min_commits:
    default: 250
    min: 1
